# Generated by Django 5.1.5 on 2025-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='lang_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='lang_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='lang_te',
            field=models.TextField(blank=True, null=True),
        ),
    ]
