# Generated by Django 5.1.5 on 2025-01-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqApp', '0002_faq_lang_bn_faq_lang_fr_faq_lang_hi_faq_lang_te'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='lang_te',
        ),
        migrations.AddField(
            model_name='faq',
            name='lang_bn_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='lang_fr_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='lang_hi_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
